apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello

  name: hello
  namespace: alpha
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: hello-app
    ports:
    - containerPort: 8080
