apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: backend
