apiVersion: v1
kind: Service
metadata:
  name: front2
  labels:
    app: front2
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: front2
