apiVersion: v1
kind: Service
metadata:
  name: front1
  labels:
    app: front1
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: front1
