apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello
    block-egress: "true"
  name: hello
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: hello-app
    ports:
    - containerPort: 8080
