apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    block-egress: "true"
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
